name: Send Commit Email

on:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      #- name: Get the latest commit message
      #id: get_commit
      #run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
      - name: Get list of modified files
        id: modified-files
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: { files } } = await github.rest.repos.getCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: context.sha
            });
            const fileNames = files.map(f => f.filename).join(' ');
            core.setOutput('files', fileNames);
      - name: Iterate and process each modified file via SSH
        run: |
          FILE_CONTENTS=""
          for file in ${{ steps.modified-files.outputs.files }}; do
              echo "Fue modificado $file"
              if [[ ! "$file" =~ "workflow.yml" ]]; then
                  echo "Renombrando $file via SSH"
                  CONTENT=$(cat "$file")
                  FILE_CONTENTS="${FILE_CONTENTS}\n\n${CONTENT}"
              fi
          done
          echo "filecontents=$FILE_CONTENTS" >> $GITHUB_ENV
      - name: Mostrando el contenido de lo modificado
        run: echo "The filename is ${{ env.filecontents }}"
