name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  rename-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read content from file
        id: read-file
        run: |
          FILENAME=$(cat images_name/servicio-apis.txt)
          echo "filename=$FILENAME" >> $GITHUB_ENV

      - name: Get list of modified files
        id: modified-files
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: { files } } = await github.rest.repos.getCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: context.sha
            });
            const fileNames = files.map(f => f.filename).join(' ');
            core.setOutput('fileNames', fileNames);
      - name: procesando
        run: |
          CONTENTS=();
          FILESNAMES=();
          for file in ${{ steps.modified-files.outputs.fileNames }}; do
            echo "Fue modificado $file"
            if [[ ! "$file" =~ "workflow.yml" && ! "$file" =~ "email.yml" ]]; then
              echo "Renombrando $file via SSH"
              modified_file=$(echo "$file" | sed 's|images_name/||g' | sed 's|.txt||g')
              CONTENT=$(cat "$file")
              CONTENTS+=("$CONTENT")
              FILESNAMES+=("$modified_file")
            fi
          done
          echo "CONTENTS=${CONTENTS[@]}"
          echo "FILESNAMES=${FILESNAMES[@]}"
          echo "contens=${CONTENTS[@]}" >> $GITHUB_ENV
          echo "filesnames=${FILESNAMES[@]}" >> $GITHUB_ENV
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            FILE_CONTENTS=""
            contens=(${{ env.contens }})
            filesnames=(${{ env.filesnames }})
            for i in "${!contens[@]}"; do
              conten="${contens[$i]}"
              filename="${filesnames[$i]}"
              FILE_CONTENTS=$(printf "%s_%s" "$filename" "$conten")
              echo "Nombre completo:: $FILE_CONTENTS"
              gp="galileo-newdev-$filename"
              ssh -i ~/id_rsaalain mome@192.168.0.98 "
                filename='$filename';
                conten='$conten';
                gp='$gp';
                if [[ \"\$filename\" == *\"webapp\"* ]]; then
                  gp=\"galileo-newdev-webapp\";
                  echo \"gp==\$gp\";
                  cont=\$(docker ps | grep webapp | awk '{print \$13}') &&
                  if [[ -n \"\$cont\" ]]; then
                    docker stop webapp &&
                    docker rm webapp
                  fi;
                  imgtmp=\$(docker images | grep \$gp | awk '{print \$1}') &&
                  echo \"imgtmp==\$imgtmp\";
                  if [[ -n \"\$imgtmp\" ]]; then
                    imgtmp1=\$(docker images | grep \$gp | awk '{print \$1}') &&
                    vertmp1=\$(docker images | grep \$gp | awk '{print \$2}') &&
                    if [[ -n \"\$imgtmp1\" ]]; then
                      echo \"eliminando imagen Webapp \$imgtmp1:\$vertmp1\"
                      docker rmi -f \$imgtmp1:\$vertmp1
                    fi;
                  fi
                  docker commit servicio-web galileo-newdev-webapp
                fi;
                img=\$(docker images | grep \$gp | awk '{print \$1}') &&
                echo \"img==\$img\";
                if [[ -n \"\$img\" ]]; then
                  echo 'ANTES DE deleteName';
                  deleteName=\$(ls /home/mome/docker/galileo-docker-images/ | grep \$filename) &&
                  echo \"deleteName=\$deleteName\";
                  if [[ -n \"\$deleteName\" ]]; then
                    mv /home/mome/docker/galileo-docker-images/\$deleteName /home/mome/docker/borrar/\$deleteName &&
                    echo \"FUE MOVIDO EL ARCHIVO \$deleteName\";
                  fi;
                  echo 'DESPUES DE deleteName';
                  img1=\$(docker images | grep 80.84.132.104:5001/galileo/\$filename | awk '{print \$1}') &&
                  ver1=\$(docker images | grep 80.84.132.104:5001/galileo/\$filename | awk '{print \$2}') &&
                  if [[ -n \"\$img1\" ]]; then
                    echo \"eliminando imagen1 \$img1:\$ver1\"
                    docker rmi -f \$img1:\$ver1
                  fi;
                  img2=\$(docker images | grep galileo/\$filename | awk '{print \$1}') &&
                  ver2=\$(docker images | grep galileo/\$filename | awk '{print \$2}') &&
                  if [[ -n \"\$img2\" ]]; then
                    echo \"eliminando imagen2 \$img2:\$ver2\"
                    docker rmi -f \$img2:\$ver2
                  fi;
                  docker tag \$gp 80.84.132.104:5001/galileo/\$filename:\$conten &&
                  docker tag \$gp galileo/\$filename:\$conten &&
                  docker save -o \"/home/mome/docker/galileo-docker-images/\${filename}_\$conten.tar.gz\" galileo/\$filename:\$conten &&
                  serv=\"${filename/servicio-/}\"
                  echo \"serv==\$serv\"
                  sed -i \"/\$serv/d\" /home/mome/docker/galileo-install/galileo-compose/.env
                  echo \"\${serv}_version=\$conten\" >> /home/mome/docker/galileo-install/galileo-compose/.env
                  cat /home/mome/docker/galileo-install/galileo-compose/.env
                  echo '********************************************'
                  sed -i \"/\$serv/d\" /home/mome/docker/galileo-install/docker/env
                  echo \"\${serv}_version=\$conten\" >> /home/mome/docker/galileo-install/docker/env
                  cat /home/mome/docker/galileo-install/docker/env
                  rm /home/mome/docker/borrar/*.* 
                  if [[ \"\$filename\" == *\"webapp\"* ]]; then
                    cd /home/mome/docker/galileo-install/galileo-compose &&
                    docker compose up app -d
                  fi;
                fi;
                echo 'GREPPPPP'"
            done
            exit
